# nuc-api Deployment
# Defines the deployment of the app running in a pod on any worker node
apiVersion: batch/v1
kind: CronJob
metadata:
  name: on-hour
spec:
  schedule: "* * * * *" #At every minute. https://crontab.guru/
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: on-hour
            image: leaver2000/nuc-api:1.0.0
            imagePullPolicy: IfNotPresent
            command: 
              - echo $(date +%Y-%m-%dT%H:%M:%SZ --utc):CronJob recorded >> app/cron.log 2>&1
              # - echo CronJob recorded >> /app/cron.log 2>&1
            # [
            #   "/bin/sh", 
            #   ""
            #   "echo hello world >> /app/cron.log 2>&1"
            #   # "NOW=$(date +'%Y-%m-%dT%H:%M:%SZ' --utc);", 
            #   # "echo '${NOW}: CronJob recorded' >> /app/cron.log 2>&1'"
            #   ]
          restartPolicy: OnFailure